name: clima_link
description: "ClimaLink is your direct connection to the weather forecast. This
  application provides you with current and accurate weather information for any
  city you choose, showing you the temperature, weather description and
  corresponding icons in a clear way. Always stay prepared for your day by
  knowing the exact weather conditions, from humidity to wind speed. With
  ClimaLink, the weather forecast is always just a tap away, making your daily
  planning easier.."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  animate_do: ^4.2.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_gen: ^5.10.0
  flutter_local_notifications: ^19.2.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  formz: ^0.8.0
  geolocator: ^14.0.1
  get_it: ^8.0.3
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.0.0
  image_picker: ^1.1.2
  intl: any
  introduction_screen: ^3.1.17
  lottie: ^3.3.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.1
  shimmer: ^3.0.0
  weatherapi: ^1.1.1

dev_dependencies:
  bloc_test: ^10.0.0
  change_app_package_name: ^1.4.0
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.1
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    # Flavors Environments
    - flavors/.env.dev
    - flavors/.env.staging
    - flavors/.env.prod
    # Assets
    - assets/app-icon/
    - assets/loaders/
    - assets/icon/
    - assets/fonts/
    - assets/images/
    - assets/images/introduction/
    - assets/lotties/

  fonts:
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Light.ttf
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Medium.ttf
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-SemiBold.ttf
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Bold.ttf

flutter_native_splash:
  color: "#007AFF"
  color_dark: "#272727"
  image: "assets/app-icon/app-icon-splash.png"

  android_12:
    color: "#007AFF"
    color_dark: "#272727"
    image: "assets/app-icon/app-icon-splash.png"
    # branding: "assets/app-icon/native_splash_icon.png"
